accumulation_steps: 1
batch_size:
  train: 1
  val: 1
  test: 1

network:
  type: model.dynunet.SegNet
  params:
    norm_name: BATCH
    res_block: true
    trans_bias: true
    deep_supr_num: 3
    deep_supervision: True
    dropout: 0.0

optimizer:
  type: torch.optim.AdamW
  params:
    lr: 3.0e-4
    weight_decay: 1.0e-5

scheduler:
  type: torch.optim.lr_scheduler.CyclicLR
  params:
    base_lr: 3.0e-6
    max_lr: 5.0e-4
    cycle_momentum: False
