accumulation_steps: 1
batch_size:
  train: 2
  val: 8
  test: 1

network:
  type: model.dynunet.SegNet
  params:
    norm_name: INSTANCE
    res_block: false
    trans_bias: false
    deep_supr_num: 3
    deep_supervision: True
    dropout: 0.0

optimizer:
  type: torch.optim.SGD
  params:
    lr: 3.0e-4
    momentum: 0.99
    weight_decay: 3e-5
    nesterov: True

scheduler:
  type: torch.optim.lr_scheduler.CyclicLR
  params:
    base_lr: 3.0e-6
    max_lr: 3.0e-4