accumulation_steps: 1
batch_size:
  train: 2
  val: 8
  test: 1

network:
  type: model.swin_unetr.SegNet
  load_head: True
  params:
    depths: [ 2, 2, 2, 2 ]
    num_heads: [ 3, 6, 12, 24 ]
    feature_size: 48


optimizer:
  type: torch.optim.AdamW
  params:
    lr: 3.0e-4
    weight_decay: 1.0e-5

scheduler:
  type: torch.optim.lr_scheduler.CyclicLR
  params:
    base_lr: 3.0e-6
    max_lr: 5.0e-4
    cycle_momentum: False
