accumulation_steps: 1

batch_size:
  train: 2
  val: 8
  test: 1

network:
  type: model.SwinUNETR
  load_head: True
  params:
    depths: [ 2, 2, 2, 2 ]
    num_heads: [ 3, 6, 12, 24 ]
    feature_size: 48


optimizer:
  type: torch.optim.Adam
  params:
    lr: 3.0e-4
    weight_decay: 1.0e-5

scheduler:
  type: monai.optimizers.WarmupCosineSchedule
  params:
    warmup_steps: "@WARMUP_STEPS=0.05"
    t_total: "@TOTAL_STEPS"