defaults:
  - data: task8
  - model: dynunet
  - dataset: cache
  - optimizer: sgd
  - scheduler: warmup_cosine
  - loss_fn: dice_ce
  - _self_

name: medical_decathlon_task8
num_epochs: 3000
buffer_size: 4
num_workers: 8
accumulation_steps: 1

batch_size:
  train: 2
  val: 8
  test: 1

eval_overlap: 0.5

debug: False
track: True
val_freq: 5
val_portion: 0.15

slices_to_show: 30

save_freq: 100
save_dir: ./ckpt
save_tag: first_try

load_from_local: False
load_from_artifact: False
load_tag: first_try

self_training: False
refresh_freq: 5

