defaults:
  - data: task8.yaml
  - model: dynunet.yaml
  - _self_

name: medical_decathlon_task8
num_workers: 8
num_epochs: 3000

debug: False
track: True
val_freq: 5

save_freq: 10
save_dir: ./ckpt
save_tag: first_try

load: False
load_tag: first_try

self_training: False
refresh_freq: 5

